Scan in controller
RedHatInsights/insights-ocp-controller pull request #15
Opened 2018-05-07 14:28 UTC by lphiri

2018-05-07 14:30 UTC, lphiri commented
This depends on : https://github.com/RedHatInsights/insights-ocp-cli/pull/2

2018-05-08 14:03 UTC, gravitypriest requested changes

2018-05-08 14:03 UTC, gravitypriest commented on pkg/controller/controller.go
> +	err = ioutil.WriteFile(machineidPath, []byte("deeznuts"), 0644)
don't need to spoof machine-id anymore. see this commit

https://github.com/RedHatInsights/insights-ocp-scanner/pull/4/commits/4ed41b9f7b66a5b58cb56d8d51475c514bad3c29

2018-05-08 14:04 UTC, gravitypriest commented on pkg/controller/controller.go
> +	err = ioutil.WriteFile(machineidPath, []byte("deeznuts"), 0644)
otherwise the rest looks good

2018-05-08 16:45 UTC, gravitypriest approved these changes

2018-05-08 16:45 UTC, merged